<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!--This file represents the results of running a test suite-->
<test-results name="C:\Users\stuart\Documents\GitHub\FSharp.Puzzles\FSharp.Puzzles.Solutions.Tests.NUnit\bin\Debug\FSharp.Puzzles.Solutions.Tests.NUnit.dll" total="12" errors="6" failures="6" not-run="0" inconclusive="0" ignored="0" skipped="0" invalid="0" date="2015-04-27" time="17:51:43">
  <environment nunit-version="2.6.4.14350" clr-version="2.0.50727.8009" os-version="Microsoft Windows NT 6.2.9200.0" platform="Win32NT" cwd="C:\Program Files (x86)\NUnit 2.6.4\bin" machine-name="STUART-HP" user="stuart" user-domain="STUART-HP" />
  <culture-info current-culture="en-AU" current-uiculture="en-US" />
  <test-suite type="Assembly" name="C:\Users\stuart\Documents\GitHub\FSharp.Puzzles\FSharp.Puzzles.Solutions.Tests.NUnit\bin\Debug\FSharp.Puzzles.Solutions.Tests.NUnit.dll" executed="True" result="Failure" success="False" time="5.004" asserts="0">
    <results>
      <test-suite type="Namespace" name="FSharp" executed="True" result="Failure" success="False" time="5.003" asserts="0">
        <results>
          <test-suite type="Namespace" name="Puzzles" executed="True" result="Failure" success="False" time="5.002" asserts="0">
            <results>
              <test-suite type="Namespace" name="Solutions" executed="True" result="Failure" success="False" time="5.002" asserts="0">
                <results>
                  <test-suite type="Namespace" name="Tests" executed="True" result="Failure" success="False" time="5.001" asserts="0">
                    <results>
                      <test-suite type="TestFixture" name="NUnit2" executed="True" result="Failure" success="False" time="5.000" asserts="0">
                        <results>
                          <test-case name="FSharp.Puzzles.Solutions.Tests.NUnit2.FsCheck test 1" executed="True" result="Error" success="False" time="1.397" asserts="0">
                            <failure>
                              <message><![CDATA[System.Exception : Falsifiable, after 1 test (0 shrinks) (StdGen (1600758150,296001120)):
Label of failing property: true = false

]]></message>
                              <stack-trace><![CDATA[at <StartupCode$FsCheck>.$Runner.get_throwingRunner@343-1.Invoke(String message)
at FsCheck.Runner.check[a](Config config, a p)
at FSharp.Puzzles.Solutions.Tests.NUnit2.FsCheck test 1() in C:\Users\stuart\Documents\GitHub\FSharp.Puzzles\FSharp.Puzzles.Solutions.Tests.NUnit\FSharp.Puzzles.Solutions.Tests.NUnit.fs:line 19
]]></stack-trace>
                            </failure>
                          </test-case>
                          <test-case name="FSharp.Puzzles.Solutions.Tests.NUnit2.FsCheck test 2 (string generator)" executed="True" result="Failure" success="False" time="0.276" asserts="0">
                            <failure>
                              <message><![CDATA[Arbitrary strings-Falsifiable, after 1 test (0 shrinks) (StdGen (1610498134,296001120)):
"i"
]]></message>
                              <stack-trace><![CDATA[at NUnitRunner.nUnitRunner@7.FsCheck-IRunner-OnFinished(String , TestResult ) in C:\Users\stuart\Documents\GitHub\FSharp.Puzzles\FSharp.Puzzles.Solutions.Tests.NUnit\NUnitRunner.fs:line 15
at FsCheck.Runner.check[a](Config config, a p)
at FSharp.Puzzles.Solutions.Tests.NUnit2.FsCheck test 2 (string generator)() in C:\Users\stuart\Documents\GitHub\FSharp.Puzzles\FSharp.Puzzles.Solutions.Tests.NUnit\FSharp.Puzzles.Solutions.Tests.NUnit.fs:line 33
]]></stack-trace>
                            </failure>
                          </test-case>
                          <test-case name="FSharp.Puzzles.Solutions.Tests.NUnit2.FsCheck test 3 (registering an arbitrary type for generation)" executed="True" result="Error" success="False" time="0.225" asserts="0">
                            <failure>
                              <message><![CDATA[System.Exception : Falsifiable, after 1 test (1 shrink) (StdGen (1613692590,296001120)):
EvenInt 0
]]></message>
                              <stack-trace><![CDATA[at <StartupCode$FsCheck>.$Runner.get_throwingRunner@343-1.Invoke(String message)
at FsCheck.Runner.check[a](Config config, a p)
at FSharp.Puzzles.Solutions.Tests.NUnit2.FsCheck test 3 (registering an arbitrary type for generation)() in C:\Users\stuart\Documents\GitHub\FSharp.Puzzles\FSharp.Puzzles.Solutions.Tests.NUnit\FSharp.Puzzles.Solutions.Tests.NUnit.fs:line 61
]]></stack-trace>
                            </failure>
                          </test-case>
                          <test-case name="FSharp.Puzzles.Solutions.Tests.NUnit2.FsCheck test 4 (and properties)" executed="True" result="Error" success="False" time="0.039" asserts="0">
                            <failure>
                              <message><![CDATA[System.Exception : Falsifiable, after 1 test (0 shrinks) (StdGen (1615960892,296001120)):
Label of failing property: 2 != 3

]]></message>
                              <stack-trace><![CDATA[at <StartupCode$FsCheck>.$Runner.get_throwingRunner@343-1.Invoke(String message)
at FsCheck.Runner.check[a](Config config, a p)
at FSharp.Puzzles.Solutions.Tests.NUnit2.FsCheck test 4 (and properties)() in C:\Users\stuart\Documents\GitHub\FSharp.Puzzles\FSharp.Puzzles.Solutions.Tests.NUnit\FSharp.Puzzles.Solutions.Tests.NUnit.fs:line 65
]]></stack-trace>
                            </failure>
                          </test-case>
                          <test-case name="FSharp.Puzzles.Solutions.Tests.NUnit2.FsCheck test 5 (or properties)" executed="True" result="Error" success="False" time="0.025" asserts="0">
                            <failure>
                              <message><![CDATA[System.Exception : Falsifiable, after 1 test (0 shrinks) (StdGen (1616509959,296001120)):
Labels of failing property (one or more is failing):
1 != 2
2 != 3

]]></message>
                              <stack-trace><![CDATA[at <StartupCode$FsCheck>.$Runner.get_throwingRunner@343-1.Invoke(String message)
at FsCheck.Runner.check[a](Config config, a p)
at FSharp.Puzzles.Solutions.Tests.NUnit2.FsCheck test 5 (or properties)() in C:\Users\stuart\Documents\GitHub\FSharp.Puzzles\FSharp.Puzzles.Solutions.Tests.NUnit\FSharp.Puzzles.Solutions.Tests.NUnit.fs:line 69
]]></stack-trace>
                            </failure>
                          </test-case>
                          <test-case name="FSharp.Puzzles.Solutions.Tests.NUnit2.FsCheck test 6a (stateful testing spec)" executed="True" result="Error" success="False" time="0.262" asserts="0">
                            <failure>
                              <message><![CDATA[System.Exception : Falsifiable, after 3 tests (0 shrinks) (StdGen (1617128257,296001120)):
Label of failing property: model = 2, actual = 1
[inc; inc; inc; dec]
]]></message>
                              <stack-trace><![CDATA[at <StartupCode$FsCheck>.$Runner.get_throwingRunner@343-1.Invoke(String message)
at FsCheck.Runner.check[a](Config config, a p)
at FSharp.Puzzles.Solutions.Tests.NUnit2.FsCheck test 6a (stateful testing spec)() in C:\Users\stuart\Documents\GitHub\FSharp.Puzzles\FSharp.Puzzles.Solutions.Tests.NUnit\FSharp.Puzzles.Solutions.Tests.NUnit.fs:line 101
]]></stack-trace>
                            </failure>
                          </test-case>
                          <test-case name="FSharp.Puzzles.Solutions.Tests.NUnit2.FsCheck test 6b (stateful testing command series)" executed="True" result="Error" success="False" time="0.062" asserts="0">
                            <failure>
                              <message><![CDATA[System.Exception : Falsifiable, after 19 tests (8 shrinks) (StdGen (1619890218,296001120)):
Label of failing property: model = 2, actual = 1
[inc; inc; inc; dec]
]]></message>
                              <stack-trace><![CDATA[at <StartupCode$FsCheck>.$Runner.get_throwingRunner@343-1.Invoke(String message)
at FsCheck.Runner.check[a](Config config, a p)
at FSharp.Puzzles.Solutions.Tests.NUnit2.FsCheck test 6b (stateful testing command series)() in C:\Users\stuart\Documents\GitHub\FSharp.Puzzles\FSharp.Puzzles.Solutions.Tests.NUnit\FSharp.Puzzles.Solutions.Tests.NUnit.fs:line 134
]]></stack-trace>
                            </failure>
                          </test-case>
                          <test-case name="FSharp.Puzzles.Solutions.Tests.NUnit2.FsUnit test 1" executed="True" result="Failure" success="False" time="0.053" asserts="1">
                            <failure>
                              <message><![CDATA[  Expected and actual are both <Microsoft.FSharp.Collections.FSharpList`1[System.Int32]>
  Values differ at index [3]
]]></message>
                              <stack-trace><![CDATA[at FSharp.Puzzles.Solutions.Tests.NUnit2.FsUnit test 1() in C:\Users\stuart\Documents\GitHub\FSharp.Puzzles\FSharp.Puzzles.Solutions.Tests.NUnit\FSharp.Puzzles.Solutions.Tests.NUnit.fs:line 138
]]></stack-trace>
                            </failure>
                          </test-case>
                          <test-case name="FSharp.Puzzles.Solutions.Tests.NUnit2.FsUnit test 2" executed="True" result="Failure" success="False" time="0.020" asserts="1">
                            <failure>
                              <message><![CDATA[  Expected: not 1
  But was:  1
]]></message>
                              <stack-trace><![CDATA[at FSharp.Puzzles.Solutions.Tests.NUnit2.FsUnit test 2() in C:\Users\stuart\Documents\GitHub\FSharp.Puzzles\FSharp.Puzzles.Solutions.Tests.NUnit\FSharp.Puzzles.Solutions.Tests.NUnit.fs:line 142
]]></stack-trace>
                            </failure>
                          </test-case>
                          <test-case name="FSharp.Puzzles.Solutions.Tests.NUnit2.FsUnit test 3" executed="True" result="Failure" success="False" time="0.022" asserts="1">
                            <failure>
                              <message><![CDATA[  Expected: 10.220000000000001d +/- 0.10000000000000001d
  But was:  10.1d
]]></message>
                              <stack-trace><![CDATA[at FSharp.Puzzles.Solutions.Tests.NUnit2.FsUnit test 3() in C:\Users\stuart\Documents\GitHub\FSharp.Puzzles\FSharp.Puzzles.Solutions.Tests.NUnit\FSharp.Puzzles.Solutions.Tests.NUnit.fs:line 146
]]></stack-trace>
                            </failure>
                          </test-case>
                          <test-case name="FSharp.Puzzles.Solutions.Tests.NUnit2.FsUnit test 4 (should throw exception)" executed="True" result="Failure" success="False" time="0.035" asserts="1">
                            <failure>
                              <message><![CDATA[  Expected: <System.Exception>
  But was:  no exception thrown
]]></message>
                              <stack-trace><![CDATA[at FSharp.Puzzles.Solutions.Tests.NUnit2.FsUnit test 4 (should throw exception)() in C:\Users\stuart\Documents\GitHub\FSharp.Puzzles\FSharp.Puzzles.Solutions.Tests.NUnit\FSharp.Puzzles.Solutions.Tests.NUnit.fs:line 150
]]></stack-trace>
                            </failure>
                          </test-case>
                          <test-case name="FSharp.Puzzles.Solutions.Tests.NUnit2.Unquote test 1" executed="True" result="Failure" success="False" time="2.099" asserts="0">
                            <failure>
                              <message><![CDATA[

([3; 2; 1; 0] |> List.map ((+) 1)) = [1 + 3..1 + 0]
[4; 3; 2; 1] = [4..1]
[4; 3; 2; 1] = []
false
]]></message>
                              <stack-trace><![CDATA[at Microsoft.FSharp.Core.Operators.Raise[T](Exception exn)
at FSharp.Puzzles.Solutions.Tests.NUnit2.Unquote test 1() in C:\Users\stuart\Documents\GitHub\FSharp.Puzzles\FSharp.Puzzles.Solutions.Tests.NUnit\FSharp.Puzzles.Solutions.Tests.NUnit.fs:line 154
]]></stack-trace>
                            </failure>
                          </test-case>
                        </results>
                      </test-suite>
                    </results>
                  </test-suite>
                </results>
              </test-suite>
            </results>
          </test-suite>
        </results>
      </test-suite>
    </results>
  </test-suite>
</test-results>